// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aggoimfswolyfubzsjsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZ29pbWZzd29seWZ1YnpzanNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTgxNjksImV4cCI6MjA2NTQ5NDE2OX0.VCtJ5c_tNsoZjWdwgcEBu9YNfGNQSwgesusNBkYV3Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);